### ISSUE TITLE
Add WGANGP to comparison

### ISSUE THREAD

**Issue by htt210** [andrewgordonwilson/bayesgan#4]
Hi Andrew,
I've just done some experiments with WGAN with Gradient Penalty (Improved Training of Wasserstein GANs, Gulrajani et al.) and found that it can converge to a reasonable solution on the synthetic dataset. Although WGANGP does not converge as fast as bayesgan, I think it would be nice if you could add WGANGP to the baselines in your experiments.
Here is the output of my (very bad) implementation of WGANGP after 8000 iterations
```
nx = 100
nz = 10
batchSize = 64
Gconfig = [('Linear', (nz, 1000)), ('ReLU', ()), ('Linear', (1000, nx))]
Dconfig = [('Linear', (nx, 1000)), ('ReLU', ()), ('Linear', (1000, 1))]
optimizer = 'Adam'
optimParams = {'lr': 1e-4, 'betas': (0.5, 0.9)}
```

![iter_8000](https://user-images.githubusercontent.com/16357422/33813687-92ec4f54-de79-11e7-8029-c265b24133e8.png)

**Comment by ysaatchi** [comment]
This is cool -- a nice extension may be to run WGAN with GP on CIFAR or MNIST and see if you get better semi-supervised results.
