### ISSUE TITLE
Different batch_norm for different gen_generation

### ISSUE THREAD

**Issue by chunhanl** [andrewgordonwilson/bayesgan#6]
I'm just wondering, shouldn't we use independent batch_norm variables for each generation of the generator ?

**Comment by ysaatchi** [comment]
I believe we do, what do you mean by "each generation"?

**Comment by chunhanl** [comment]
Dear Yunus,
It appears that you fixed it in latest commit, thanks a lot!!
(The generations refers to the dictionary defined in bgan_models.py (line 136), where you placed the generators and the MC samples.)

By the way, I have another question. Where is the difference between ensembles of 20 GANs and BayesGAN with Jg=10 Jd=1 M=2 ? The parameter samples are trained independently in the provided code, which is similar to training 20 GANs independently. In which part makes the network Bayesian and leads to better performance in semi-supervised learning?

**Comment by ysaatchi** [comment]
Hi,

BayesGAN is not the same as 20 independent GANs, intuitively because each discriminator has to discriminate against samples generated by all generators, and each generator has to jointly fool all discriminators in the mix.

**Comment by chunhanl** [comment]
Got it
Thanks for helping ~
