### ISSUE TITLE
Multiple discriminator MC samples

### ISSUE THREAD

**Issue by ysaibhargav** [andrewgordonwilson/bayesgan#7]
Dear authors, great work on the BayesGAN paper and code, congratulations! I had a question about your code - is there currently support for multiple discriminator MC samples (J_d > 1)? If not, is there any reason why it's left out? Thanks!

**Comment by ysaatchi** [comment]
Thanks!! :) 

Yes there is, it's default is 1, but certainly do experiment with J_d > 1 (should be one of the args)

**Comment by JINGTING92** [comment]
Thanks for your code, but I found that the discrinimator loss often becomes Nan when setting J_d > 1, could anyone explain this?

**Comment by erjingjing** [comment]
？I am a fresh man，sorry，i do not write any code

At 2019-02-28 12:11:43, "JINGTING" <notifications@github.com> wrote:


Thanks for your code, but I found that the discrinimator loss often becomes Nan when setting J_d > 1, could anyone explain this?
